# Generated by Django 5.2 on 2025-04-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=255, unique=True)),
                ('product_id', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sku', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
